### PR TITLE
Add Spanish translation

### PR DESCRIPTION
**Pull request by corp-0**
**When merged this pull request will:**
- Add Spanish translation for everything you have so far

- I just omitted "cool battery" from kat_aceCirculation because I don't know how to translate that.

### CODE REVIEW

**Comment by Katalam** [comment]
I don‘t even know if this is the right english translation, but thanks a lot.

**Comment by Katalam** [comment]
this is the thing i mean: https://www.bueroshop24.de/ugsshoppictures/img/27/28/Zoom_m1453258.jpg/l/2-ezetil-k%C3%BChlakkus-423071

**Comment by corp-0** [comment]
can you reopen this PR? After consultation with a nurse friend, I can add the proper name for that thing and correct a couple of terms to reflect better what the actual medics say.

**Comment by Katalam** [comment]
Actually I think I can’t but you could start a new PR.

**Pull request merged**
